### ISSUE TITLE
[Bug] Friends list won't load on latest stable

### ISSUE THREAD

**Issue by KazyEXE** [vrcx-team/VRCX#1002]
This was happening with a new Nightly version a few weeks back so I switched over to Stable, but the latest Stable has the same issue. My friends list doesn't load, I only see the "ME" section

**To Reproduce**
I know this isn't for everyone, but I don't know 
1. Download the latest version
2. Login

Here is the console error:
```
app.js:5426 Uncaught (in promise) System.InvalidOperationException: Could not execute method: ExecuteNonQuery(CREATE TABLE IF NOT EXISTS 8YwOXypxeb_feed_gps (id INTEGER PRIMARY KEY, created_at TEXT, user_id TEXT, display_name TEXT, location TEXT, world_name TEXT, previous_location TEXT, time INTEGER, group_name TEXT), ) 
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x87AF001F): SQL logic error
unrecognized token: "8YwOXypxeb_feed_gps"
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at VRCX.SQLiteLegacy.ExecuteNonQuery(String sql, IDictionary`2 args)
   at InvokeStub_SQLiteLegacy.ExecuteNonQuery(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CefSharp.Internals.JavascriptObjectRepository.TryCallMethodAsync(Int64 objectId, String name, Object[] parameters)
   --- End of inner exception stack trace ---
   at CefSharp.Internals.JavascriptObjectRepository.TryCallMethodAsync(Int64 objectId, String name, Object[] parameters) in C:\projects\cefsharp\CefSharp\Internals\JavascriptObjectRepository.cs:line 538
```

**Expected behavior**
My friends list to load

**Screenshots**
![image](https://github.com/user-attachments/assets/418f4952-d8f2-4f7b-87ae-bb60563fb657)

**What version you are running**
2024.12.03

**Comment by SalbugVR** [comment]
Does it stay in that state indefinitely? For me it would eventually load after a couple of seconds.

**Comment by Natsumi-sama** [comment]
With that error I think they database is cooked, try repair it with this guide https://github.com/vrcx-team/VRCX/wiki#how-to-repair-vrcx-database

**Comment by KazyEXE** [comment]
Even though the database still works after going back to an earlier version?
