### ISSUE TITLE
[Bug] Post-Login UI Rendering Issue

### ISSUE THREAD

**Issue by refiaa** [vrcx-team/VRCX#909]
**Describe the bug**
After logging out and logging back in, the friend window is displayed but the main window fails to appear properly. The main window shows as black, and the friend window is positioned incorrectly on the far left instead of on the right side.
To Reproduce

**Open the application**
Log out of your account
Log back in
Observe that the friend window appears, but the main window is black
Notice that the friend window is positioned on the far left instead of the right side

**Expected behavior**
Both the main window and friend window should be displayed correctly. The main window should show content (not be black), and the friend window should be positioned on the right side.

**Screenshots**

![スクリーンショット 2024-09-10 185026](https://github.com/user-attachments/assets/5a06195a-a426-4205-8583-747bc9e13d77)

*Friend information is visible on the window, but details have been edited for privacy.*

**What version you are running**
Version: `VRCX 2024.09.02`

**Comment by Natsumi-sama** [comment]
Could you press `Ctrl + Shift + I` and select the console tab and check to see if you have any errors listed?

**Comment by refiaa** [comment]
this is what i've got in cosole tab, but i cant reproduced on other clients - meaning other users' systems or environments. Therefore, the problem may be specific to my local files or system configuration.

Trynna debug in my local environment, after I checked app.js, it doesn't seem possible to fix it easily. It might be better to reinstall all the files of VRCX on my own PC.

```
app.js:488 Uncaught (in promise) Error: 401: Missing Credentials
    at app.js:488:27
```

```
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at S (app.js:9631:23)
    at Array.sort (<anonymous>)
    at Array.<anonymous> (vue.common.prod.js:6:6188)
    at e.computed.friendsGroup1 (app.js:9807:33)
    at mn.get (vue.common.prod.js:6:26695)
    at mn.evaluate (vue.common.prod.js:6:27835)
    at Sn.friendsGroup1 (vue.common.prod.js:6:29739)
    at e.methods.updateOnlineFriendCoutner (app.js:9619:46)
    at Object.<anonymous> (app.js:9090:14)
    at g.$emit (app.js:337:25)
```

```
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at S (app.js:9631:23)
    at Array.sort (<anonymous>)
    at Array.<anonymous> (vue.common.prod.js:6:6188)
    at e.computed.friendsGroup2 (app.js:9825:33)
    at mn.get (vue.common.prod.js:6:26695)
    at mn.evaluate (vue.common.prod.js:6:27835)
    at Sn.friendsGroup2 (vue.common.prod.js:6:29739)
    at Sn.eval (eval at Xa (vue.common.prod.js:6:92034), <anonymous>:3:210384)
    at e._render (vue.common.prod.js:6:35382)
    at Sn.i (vue.common.prod.js:6:68393)
```

```
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at S (app.js:9631:23)
    at Array.sort (<anonymous>)
    at Array.<anonymous> (vue.common.prod.js:6:6188)
    at e.computed.friendsGroup1 (app.js:9807:33)
    at mn.get (vue.common.prod.js:6:26695)
    at mn.evaluate (vue.common.prod.js:6:27835)
    at Sn.friendsGroup1 (vue.common.prod.js:6:29739)
    at e.methods.updateOnlineFriendCoutner (app.js:9619:46)
    at Object.<anonymous> (app.js:9090:14)
    at g.$emit (app.js:337:25)

```


```

TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at S (app.js:9631:23)
    at Array.sort (<anonymous>)
    at Array.<anonymous> (vue.common.prod.js:6:6188)
    at e.computed.friendsGroup2 (app.js:9825:33)
    at mn.get (vue.common.prod.js:6:26695)
    at mn.evaluate (vue.common.prod.js:6:27835)
    at Sn.friendsGroup2 (vue.common.prod.js:6:29739)
    at Sn.eval (eval at Xa (vue.common.prod.js:6:92034), <anonymous>:3:210384)
    at e._render (vue.common.prod.js:6:35382)
    at Sn.i (vue.common.prod.js:6:68393)
```

```
TypeError: Cannot read properties of undefined (reading 'localeCompare')
    at S (app.js:9631:23)
    at Array.sort (<anonymous>)
    at Array.<anonymous> (vue.common.prod.js:6:6188)
    at e.computed.friendsGroup3 (app.js:9837:33)
    at mn.get (vue.common.prod.js:6:26695)
    at mn.evaluate (vue.common.prod.js:6:27835)
    at Sn.friendsGroup3 (vue.common.prod.js:6:29739)
    at Sn.eval (eval at Xa (vue.common.prod.js:6:92034), <anonymous>:3:211991)
    at e._render (vue.common.prod.js:6:35382)
    at Sn.i (vue.common.prod.js:6:68393)
Ue @ vue.common.prod.js:6
Show 1 more frame
Show less
app.js:25954 

```

**Comment by Natsumi-sama** [comment]
uh best solution for you now would be to downgrade VRCX, we will fix this bug in the next release.

**Comment by refiaa** [comment]
I've submitted a pull request that addresses the issue of rendering issue. 

https://github.com/vrcx-team/VRCX/pull/910
